export const TOGGLE_USER_BLOCK_START = 'TOGGLE_USER_BLOCK_START';
export const TOGGLE_USER_BLOCK_SUCCESS = 'TOGGLE_USER_BLOCK_SUCCESS';
export const TOGGLE_USER_BLOCK_FAILURE = 'TOGGLE_USER_BLOCK_FAILURE';
